server:
  port: 8080
 
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password: kitteloridy
  jpa:
    hibernate:
      ddl-auto: create
    
